
version: '3'

services:

  shard3svr1:
    container_name: shard3svr1
    image: mongo
    command: mongod --shardsvr --replSet rsjuan --bind_ip_all --port 27017 --dbpath /data/db
    ports:
      - 50013:27017
    volumes:
      - shard3svr1:/data/db

  shard3svr2:
    container_name: shard3svr2
    image: mongo
    command: mongod --shardsvr --replSet rsjuan --bind_ip_all --port 27017 --dbpath /data/db
    ports:
      - 50014:27017
    volumes:
      - shard3svr2:/data/db

  shard3svr3:
    container_name: shard3svr3
    image: mongo
    command: mongod --shardsvr --replSet rsjuan --bind_ip_all --port 27017 --dbpath /data/db
    ports:
      - 50015:27017
    volumes:
      - shard3svr3:/data/db

volumes:
  shard3svr1: {}
  shard3svr2: {}
  shard3svr3: {}

